-- CLEANUP
DROP TABLE NOTIFICATIONS CASCADE CONSTRAINTS;
DROP TABLE FAVORITES CASCADE CONSTRAINTS;
DROP TABLE REVIEWS CASCADE CONSTRAINTS;
DROP TABLE PAYMENTS CASCADE CONSTRAINTS;
DROP TABLE ORDER_ITEMS CASCADE CONSTRAINTS;
DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE CART_ITEMS CASCADE CONSTRAINTS;
DROP TABLE CART CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_IMAGES CASCADE CONSTRAINTS;
DROP TABLE PRODUCTS CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE SECURITY_QUESTIONS CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;

DROP SEQUENCE USER_SEQ;
DROP SEQUENCE CATEGORY_SEQ;
DROP SEQUENCE PRODUCT_SEQ;
DROP SEQUENCE PRODUCT_IMAGE_SEQ;
DROP SEQUENCE CART_SEQ;
DROP SEQUENCE CARTITEM_SEQ;
DROP SEQUENCE ORDER_SEQ;
DROP SEQUENCE ORDERITEM_SEQ;
DROP SEQUENCE PAYMENT_SEQ;
DROP SEQUENCE REVIEW_SEQ;
DROP SEQUENCE FAVORITE_SEQ;
DROP SEQUENCE NOTIFICATION_SEQ;


--------------------------------------------------
-- SECURITY_QUESTIONS
--------------------------------------------------
CREATE TABLE SECURITY_QUESTIONS (
    QUESTION_ID NUMBER PRIMARY KEY,
    QUESTION_TEXT VARCHAR2(255) NOT NULL
);

--------------------------------------------------
-- USERS
--------------------------------------------------
CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(150) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(10) CHECK (ROLE IN ('BUYER','SELLER')),
    MOBILE_NUMBER NUMBER NOT NULL,
    BUSINESS_NAME VARCHAR2(150),
    ADDRESS VARCHAR2(255),
    SECURITY_QUESTION_ID NUMBER,
    SECURITY_ANSWER VARCHAR2(255),

    CONSTRAINT FK_USER_SECURITY_QUESTION
    FOREIGN KEY (SECURITY_QUESTION_ID)
    REFERENCES SECURITY_QUESTIONS(QUESTION_ID)
);

CREATE SEQUENCE USER_SEQ 
START WITH 1 
INCREMENT BY 1 
NOCACHE 
NOCYCLE;
--------------------------------------------------
-- CATEGORY
--------------------------------------------------
CREATE TABLE CATEGORY (
    CATEGORY_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE CATEGORY_SEQ START WITH 1 INCREMENT BY 1;

--------------------------------------------------
-- PRODUCTS
--------------------------------------------------
CREATE TABLE PRODUCTS (
    PRODUCT_ID NUMBER PRIMARY KEY,

    NAME VARCHAR2(255) NOT NULL,
    DESCRIPTION VARCHAR2(3000),

    PRICE NUMBER(10,2) NOT NULL CHECK (PRICE >= 0),
    MRP NUMBER(10,2) NOT NULL,

    STOCK NUMBER DEFAULT 0 CHECK (STOCK >= 0),
    INVENTORY_THRESHOLD NUMBER DEFAULT 0 CHECK (INVENTORY_THRESHOLD >= 0),

    SELLER_ID NUMBER NOT NULL,
    CATEGORY_ID NUMBER,

    -- ? Table-level check constraint
    CONSTRAINT CHK_MRP_PRICE CHECK (MRP >= PRICE),

    CONSTRAINT FK_PRODUCT_SELLER
        FOREIGN KEY (SELLER_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT FK_PRODUCT_CATEGORY
        FOREIGN KEY (CATEGORY_ID)
        REFERENCES CATEGORY(CATEGORY_ID)
);

CREATE SEQUENCE PRODUCT_SEQ START WITH 1 INCREMENT BY 1;

--------------------------------------------------
-- PRODUCT IMAGES
--------------------------------------------------
CREATE TABLE PRODUCT_IMAGES (
    IMAGE_ID NUMBER PRIMARY KEY,
    PRODUCT_ID NUMBER NOT NULL,
    IMAGE_URL VARCHAR2(500) NOT NULL,

    CONSTRAINT FK_PRODUCT_IMAGE
    FOREIGN KEY (PRODUCT_ID)
    REFERENCES PRODUCTS(PRODUCT_ID)
    ON DELETE CASCADE
);

CREATE SEQUENCE PRODUCT_IMAGE_SEQ START WITH 1 INCREMENT BY 1;

--------------------------------------------------
-- CART
--------------------------------------------------
CREATE TABLE CART (
    CART_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER UNIQUE NOT NULL,

    CONSTRAINT FK_CART_USER
    FOREIGN KEY (USER_ID)
    REFERENCES USERS(USER_ID)
);

CREATE SEQUENCE CART_SEQ START WITH 1 INCREMENT BY 1;

--------------------------------------------------
-- CART ITEMS
--------------------------------------------------
CREATE TABLE CART_ITEMS (
    CART_ITEM_ID NUMBER PRIMARY KEY,
    CART_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    QUANTITY NUMBER DEFAULT 1,

    CONSTRAINT FK_CARTITEM_CART
    FOREIGN KEY (CART_ID)
    REFERENCES CART(CART_ID),

    CONSTRAINT FK_CARTITEM_PRODUCT
    FOREIGN KEY (PRODUCT_ID)
    REFERENCES PRODUCTS(PRODUCT_ID),

    CONSTRAINT UQ_CART_PRODUCT UNIQUE (CART_ID, PRODUCT_ID)
);

CREATE SEQUENCE CARTITEM_SEQ START WITH 1 INCREMENT BY 1;

--------------------------------------------------
-- ORDERS
--------------------------------------------------
CREATE TABLE ORDERS (
    ORDER_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,

    ORDER_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(30) DEFAULT 'PENDING',
    TOTAL_AMOUNT NUMBER(10,2) CHECK (TOTAL_AMOUNT >= 0),

    SHIPPING_NAME VARCHAR2(100),
    SHIPPING_PHONE VARCHAR2(20),
    SHIPPING_ADDRESS VARCHAR2(255),
    SHIPPING_PINCODE VARCHAR2(10),
    PAYMENT_METHOD VARCHAR2(50),

    CONSTRAINT FK_ORDER_USER
    FOREIGN KEY (USER_ID)
    REFERENCES USERS(USER_ID),

    CONSTRAINT CHK_ORDER_STATUS
    CHECK (STATUS IN (
        'PENDING',
        'ACCEPTED',
        'REJECTED',
        'DELIVERED',
        'CANCELLED'
    ))
);

CREATE SEQUENCE ORDER_SEQ START WITH 1 INCREMENT BY 1;

--------------------------------------------------
-- ORDER ITEMS
--------------------------------------------------
CREATE TABLE ORDER_ITEMS (
    ORDER_ITEM_ID NUMBER PRIMARY KEY,
    ORDER_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    QUANTITY NUMBER NOT NULL,
    PRICE NUMBER(10,2) NOT NULL,

    CONSTRAINT FK_ORDERITEM_ORDER
    FOREIGN KEY (ORDER_ID)
    REFERENCES ORDERS(ORDER_ID),

    CONSTRAINT FK_ORDERITEM_PRODUCT
    FOREIGN KEY (PRODUCT_ID)
    REFERENCES PRODUCTS(PRODUCT_ID),

    CONSTRAINT UQ_ORDER_PRODUCT UNIQUE (ORDER_ID, PRODUCT_ID)
);

CREATE SEQUENCE ORDERITEM_SEQ START WITH 1 INCREMENT BY 1;

--------------------------------------------------
-- PAYMENTS
--------------------------------------------------
CREATE TABLE PAYMENTS (
    PAYMENT_ID NUMBER PRIMARY KEY,
    ORDER_ID NUMBER NOT NULL,
    PAYMENT_METHOD VARCHAR2(50),
    PAYMENT_STATUS VARCHAR2(30),
    AMOUNT NUMBER(10,2) CHECK (AMOUNT >= 0),
    PAYMENT_DATE DATE DEFAULT SYSDATE,

    CONSTRAINT FK_PAYMENT_ORDER
    FOREIGN KEY (ORDER_ID)
    REFERENCES ORDERS(ORDER_ID)
);

CREATE SEQUENCE PAYMENT_SEQ START WITH 1 INCREMENT BY 1;

--------------------------------------------------
-- REVIEWS
--------------------------------------------------
CREATE TABLE REVIEWS (
    REVIEW_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    RATING NUMBER(1) NOT NULL CHECK (RATING BETWEEN 1 AND 5),
    COMMENT_TEXT VARCHAR2(1000),
    REVIEW_DATE DATE DEFAULT SYSDATE,

    CONSTRAINT FK_REVIEW_USER
    FOREIGN KEY (USER_ID)
    REFERENCES USERS(USER_ID),

    CONSTRAINT FK_REVIEW_PRODUCT
    FOREIGN KEY (PRODUCT_ID)
    REFERENCES PRODUCTS(PRODUCT_ID),

    CONSTRAINT UQ_USER_PRODUCT_REVIEW UNIQUE (USER_ID, PRODUCT_ID)
);

CREATE SEQUENCE REVIEW_SEQ START WITH 1 INCREMENT BY 1;

--------------------------------------------------
-- FAVORITES / WISHLIST
--------------------------------------------------
-- 1. Create the Sequence for Primary Key IDs
CREATE SEQUENCE FAVORITE_SEQ 
    START WITH 1 
    INCREMENT BY 1;

-- 2. Create the Favorites Table
CREATE TABLE FAVORITES (
    FAVORITE_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    ADDED_AT TIMESTAMP DEFAULT SYSTIMESTAMP, -- Single, high-precision timestamp

    -- Foreign Key to the Users Table
    CONSTRAINT FK_FAV_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE, -- If a user is deleted, their favorites are removed

    -- Foreign Key to the Products Table
    CONSTRAINT FK_FAV_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCTS(PRODUCT_ID)
        ON DELETE CASCADE, -- If a product is deleted, it's removed from all wishlists

    -- Unique Constraint: One user can only favorite a specific product once
    CONSTRAINT UQ_USER_PRODUCT UNIQUE (USER_ID, PRODUCT_ID)
);

--------------------------------------------------
-- NOTIFICATIONS
--------------------------------------------------
CREATE TABLE NOTIFICATIONS (
    NOTIFICATION_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL ,
    MESSAGE VARCHAR2(500),
    IS_READ NUMBER(1) DEFAULT 0,
    CREATED_AT DATE DEFAULT SYSDATE,

    CONSTRAINT FK_NOTIFICATION_USER
    FOREIGN KEY (USER_ID)
    REFERENCES USERS(USER_ID)
);

CREATE SEQUENCE NOTIFICATION_SEQ START WITH 1 INCREMENT BY 1;


------------------------------------------------------------------
INSERT INTO SECURITY_QUESTIONS (QUESTION_ID, QUESTION_TEXT) VALUES (1, 'What was the name of your first pet?');
INSERT INTO SECURITY_QUESTIONS (QUESTION_ID, QUESTION_TEXT) VALUES (2, 'In what city were you born?');
INSERT INTO SECURITY_QUESTIONS (QUESTION_ID, QUESTION_TEXT) VALUES (3, 'What was your childhood nickname?');
INSERT INTO SECURITY_QUESTIONS (QUESTION_ID, QUESTION_TEXT) VALUES (4, 'What is the name of your favorite book?');
INSERT INTO SECURITY_QUESTIONS (QUESTION_ID, QUESTION_TEXT) VALUES (5, 'What was the make of your first car?');

-- Important: If you aren't using auto-increment for this table, 
-- remember to COMMIT your changes so the Java app can see them.
--------------------------------------------------
-- INSERT DEFAULT CATEGORIES
--------------------------------------------------

INSERT INTO CATEGORY (CATEGORY_ID, NAME) VALUES (CATEGORY_SEQ.NEXTVAL, 'Electronics');

INSERT INTO CATEGORY (CATEGORY_ID, NAME) VALUES (CATEGORY_SEQ.NEXTVAL, 'Mobiles & Accessories');

INSERT INTO CATEGORY (CATEGORY_ID, NAME) VALUES (CATEGORY_SEQ.NEXTVAL, 'Laptops & Computers');

INSERT INTO CATEGORY (CATEGORY_ID, NAME) VALUES (CATEGORY_SEQ.NEXTVAL, 'Fashion & Apparel');

INSERT INTO CATEGORY (CATEGORY_ID, NAME) VALUES (CATEGORY_SEQ.NEXTVAL, 'Home & Kitchen');

INSERT INTO CATEGORY (CATEGORY_ID, NAME) VALUES (CATEGORY_SEQ.NEXTVAL, 'Books & Stationery');

INSERT INTO CATEGORY (CATEGORY_ID, NAME) VALUES (CATEGORY_SEQ.NEXTVAL, 'Beauty & Personal Care');

INSERT INTO CATEGORY (CATEGORY_ID, NAME) VALUES (CATEGORY_SEQ.NEXTVAL, 'Sports & Outdoors');
COMMIT;
