spring.application.name=revshop
server.port=8888

# Oracle Database Connection
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=RevshopFinalTeam
spring.datasource.password=revshop
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Max size for a single file
spring.servlet.multipart.max-file-size=10MB

# Max size for the entire request (if uploading multiple files)
spring.servlet.multipart.max-request-size=30MB

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

server.error.include-message=always